### ISSUE TITLE
Ordered growth for PGGB gfa file

### ISSUE THREAD

**Issue by OZTaekOppa** [marschall-lab/panacus#33]
Dear Panacus,

Thank you for developing such a great program.

I’m interested in testing the "Ordered Pangenome Growth Statistics" for a PGGB GFA file. However, the manual only provides guidance for minigraph-cactus. I attempted to run the "Ordered Pangenome Growth Statistics" for the PGGB GFA file after making a few modifications, but I wasn’t successful.

Here is the script I executed:

# Step 1a: Establish order of samples in the growth statistics
echo 'HG01891 HG02109 HG02145 HG02257 HG02486 HG02559 HG02572 HG02622 HG02630 HG02717 HG02723 HG02818 HG02886 HG03098 HG03453 HG03486 HG03516 HG03540 HG03579 NA18906 NA19240 NA21309 HG00733 HG00735 HG00741 HG01071 HG01106 HG01109 HG01123 HG01175 HG01243 HG01358 HG01361 HG01928 HG01952 HG01978 HG02055 HG02148 NA20129 HG01258 NA24385 HG03492 HG00438 HG00621 HG00673 HG02080 NA24631 N002580 N002639 N003302 N006906 N006942 N008032 N008291 N008292 N008293 N008294' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.order.samples.txt

# Step 1b: Exclude paths from reference genome CHM13 and GRCH38
grep '^P' ${INPUT_GFA} | cut -f2 | grep -ve 'chm13\|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt

# Step 2: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info panacus ordered-histgrowth -c bp -t6 -l 25,20,5,3,2 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv

# Step 3: Visualize coverage histogram and pangenome growth curve with estimated growth parameters
panacus-visualize -e ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.pdf

conda deactivate

Here is the log:
+ panacus-visualize -e /g/data/te53/t2t2024/analyses/panacus/PGGB/Ordered//chm13_grch38_hprc_ncig.fasta.gz.a8a102b.community.1.fa.a8a102b.7608fc1.ad33725.smooth.final.pggb.ordhstgrw.bp.tsv
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:25: SyntaxWarning: invalid escape sequence '\S'
  PAT_PANACUS = re.compile('^#.+panacus (\S+) (.+)')
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:117: SyntaxWarning: invalid escape sequence '\g'
  df[(t, ct, c, q)].plot.bar(color=f'C{i}', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%', ax=axs[0])
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:117: SyntaxWarning: invalid escape sequence '\g'
  df[(t, ct, c, q)].plot.bar(color=f'C{i}', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%', ax=axs[0])
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:122: SyntaxWarning: invalid escape sequence '\g'
  axs[0].plot(df.loc[1:].index, curve, '--',  color='black', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%, $k_1 X^γ$ with $k_1$={humanize_number(popt[0],1)}, γ={popt[1]:.3f})')
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:122: SyntaxWarning: invalid escape sequence '\g'
  axs[0].plot(df.loc[1:].index, curve, '--',  color='black', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%, $k_1 X^γ$ with $k_1$={humanize_number(popt[0],1)}, γ={popt[1]:.3f})')
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:140: SyntaxWarning: invalid escape sequence '\g'
  (df.loc[df.index[1]:, (t, ct, c, q)] - x).plot.bar(color=f'C{i}', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%', ax=axs[1])
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:140: SyntaxWarning: invalid escape sequence '\g'
  (df.loc[df.index[1]:, (t, ct, c, q)] - x).plot.bar(color=f'C{i}', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%', ax=axs[1])
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:146: SyntaxWarning: invalid escape sequence '\g'
  axs[1].plot(Y, '--',  color='black', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%, $k_2 X^{{-α}}$ with $k_2$={humanize_number(k2,1)}, α={alpha:.3f})')
/g/data/te53/condapkg/envs/panacus_v023/bin/panacus-visualize:146: SyntaxWarning: invalid escape sequence '\g'
  axs[1].plot(Y, '--',  color='black', label=f'coverage $\geq {c}$, quorum $\geq {q*100:.0f}$%, $k_2 X^{{-α}}$ with $k_2$={humanize_number(k2,1)}, α={alpha:.3f})')

Is there a way to successfully run the "Ordered Pangenome Growth Statistics" for a PGGB GFA file?

Any feedback would be greatly appreciated!

Cheers,

Taek

**Comment by heringerp** [comment]
Hi Taek,
 
what exactly isn't working for you? Is the .tsv outputted by `panacus ordered-histgrowth` fine?

If you want to exclude the reference sequences from the graph you can create the paths file in the following way:
```
grep '^P' ${INPUT_GFA} | cut -f2 | grep -iE 'chm13|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt
```
(use `grep -iE` instead of `grep -ve`, since only paths that should be excluded need to be listed)

The SyntaxWarnings for the python script can be ignored, they are only warnings and do not affect the result (still #34 should fix them).

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

Thank you for your prompt reply.

I followed your directions as outlined below.

Executed command (for PGGB gfa file):
qsub -o /g/data/te53/t2t2024/logs/ -v INPUT_GFA=/community.1.fa.out/community.1.fa.smooth.final.gfa ./panacus_pggb.sh

Panacus_pggb.sh: 
# Step 1a: Establish the order of samples in the growth statistics
echo 'HG01891 HG02109 HG02145 HG02257 HG02486 HG02559 HG02572 HG02622 HG02630 HG02717 HG02723 HG02818 HG02886 HG03098 HG03453 HG03486 HG03516 HG03540 HG03579 NA18906 NA19240 NA21309 HG00733 HG00735 HG00741 HG01071 HG01106 HG01109 HG01123 HG01175 HG01243 HG01358 HG01361 HG01928 HG01952 HG01978 HG02055 HG02148 NA20129 HG01258 NA24385 HG03492 HG00438 HG00621 HG00673 HG02080 NA24631 N002580 N002639 N003302 N006906 N006942 N008032 N008291 N008292 N008293 N008294' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.order.samples.txt

# Step 1b: Exclude paths from reference genome CHM13 and GRCH38
grep '^P' ${INPUT_GFA} | cut -f2 | grep -iE 'chm13|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt

# Step 2: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info panacus ordered-histgrowth -c bp -t6 -l 20,20,10,3,2 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv

# Step 3: Visualize coverage histogram and pangenome growth curve with estimated growth parameters
panacus-visualize -e ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.pdf


While Step 1a generated {OUTPUT_DIR}/pggb_hprc.order.samples.txt, the “ordered-growth plot for #bp” still shows the X-axis as consecutive numbers (0 ~ 57), instead of reflecting the sample order.

Also, I would like to confirm the correct usage of the -l 20,20,10,3,2 option in Step 2. If {OUTPUT_DIR}/pggb_hprc.order.samples.txt is set correctly, I expect to see the growth for the last 10 samples (N002580 ~ N008294). Was my option correct for reflecting this growth?

Looking forward to your feedback!

Kind regards,

Taek

**Comment by heringerp** [comment]
Hi Taek,

hmm, for me the plot shows the sample names on the x-axis. What version of panacus are you using?

With regards to the sample order: if you want to use the order of the `order.samples.txt` file you need to specify it to `panacus ordered-histgrowth` with the `-O` parameter.
The `-l` option sets the coverage values used for the different bars, i.e. it will show bars for coverage 20 (twice), coverage 10, coverage 3 and coverage 2. This means that in this calculation only basepairs are included that are visited by at least 20 haplotypes (or 10, 3, 2). See also [](https://hackmd.io/asojhSf-T8GOJOr9HQj_IA#Panacus) for an explanation. The growth will still be shown for all samples not just the last 10.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

FYI, I am using the latest conda version (v0.2.3).

I tried following your suggestions, but something seems off.

Executed script:

### Ordered Histgrowth
# Step 1: Establish the order of samples in the growth statistics (ARF, AMR, EUR, SAS, EAS, NCIG)
echo 'HG01891 HG02109 HG02145 HG02257 HG02486 HG02559 HG02572 HG02622 HG02630 HG02717 HG02723 HG02818 HG02886 HG03098 HG03453 HG03486 HG03516 HG03540 HG03579 NA18906 NA19240 NA21309 HG00733 HG00735 HG00741 HG01071 HG01106 HG01109 HG01123 HG01175 HG01243 HG01358 HG01361 HG01928 HG01952 HG01978 HG02055 HG02148 NA20129 HG01258 NA24385 HG03492 HG00438 HG00621 HG00673 HG02080 NA24631 N002580 N002639 N003302 N006906 N006942 N008032 N008291 N008292 N008293 N008294' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.order.samples.txt

# Step 2: Establish the exclude of samples in the growth statistics
echo 'chm13 grch38' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.exculde.samples.txt

# Step 3: Exclude paths from reference genome CHM13 and GRCH38
grep '^P' ${INPUT_GFA} | cut -f2 | grep -iE 'chm13|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt

# Step 4: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info panacus ordered-histgrowth -c bp -t6 -l 5,10,20,15,5 -S -e ${OUTPUT_DIR}/pggb_hprc.exculde.samples.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv

# Step 5: Visualize coverage histogram and pangenome growth curve with estimated growth parameters
panacus-visualize -e ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.pdf


It worked fine up to Step 3, but Step 4 failed. After reading more about the "ordered-histgrowth" function, I tried a few variations.

•	Command: -c bp -t6 -l 5,10,20,15,5 -S -e
o	The pggb.ordhstgrw.bp.tsv was generated, but the plot didn’t reflect the ordered names (X-axis) from Step 1.

•	Command: -c bp -t6 -l 5,10,20,15,5 -S -e -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt
o	The program complained about the -e option.
o	Error: error: a value is required for '--exclude <exclude>' but none was supplied

•	Command: -c bp -t6 -l 5,10,20,15,5 -S -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt
o	Error: error: unexpected argument 'community.1.fa.out/community.1.smooth.final.gfa' found

•	Command: -c bp -t6 -l 5,10,20,15,5 -S -e ${OUTPUT_DIR}/pggb_hprc.exclude.samples.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt
o	Same error as above:
o	Error: error: unexpected argument 'community.1.fa.out/community.1.smooth.final.gfa' found


Any suggestions?

Cheers,

Taek

**Comment by heringerp** [comment]
Hi Taek,

okay, so the plot showing numbers instead of the sample names is an issue that is fixed in the version on GitHub, however the fix is not yet included in the most recent version on conda.

For the command in step 4 try something like:
```
RUST_LOG=info panacus ordered-histgrowth -c bp -t6 -l 5,10,20,15,5 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv
```

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

Thanks so much for your help. 

Unfortunately, the issue persists. The script runs fine, but the plot still shows numbers instead of the sample names from pggb_hprc.order.samples.txt.

Should I try reinstalling the program from scratch via GitHub, or could you update the Conda version to fix the issue?

What do you think?

Cheers,

Taek

**Comment by heringerp** [comment]
Hi Taek,

unfortunately, I don't think that I can update the conda version of the package, maybe @lucaparmigiani or @danydoerr can help?

In the meantime installing from scratch via GitHub should fix the issue for you.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

Thank you for your reply.

I tried these two commands after installing it via the "From binary release" option.

Command 1:
##Step 4: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info ${PANACUS} ordered-histgrowth -c bp -t6 -l 5,10,20,15,5 -S -e ${OUTPUT_DIR}/pggb_hprc.exculde.samples.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv

Warning: /panacus-0.2.3/bin/panacus-visualize -e /panacus/PGGB/Ordered/community.11.fa.smooth.final.pggb.ordhstgrw.bp.tsv
/apps/python3/3.9.2/lib/python3.9/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "

Command 2: 
##Step 4: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info ${PANACUS} ordered-histgrowth -c bp -t6 -l 5,10,20,15,5 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ordhstgrw.bp.tsv

Error: error: unexpected argument 'community.11.fa.out/community.1.smooth.final.gfa' found


Command 1 generated a plot, but the X-axis names are still numbers. It seems the program is not properly recognising the pggb_hprc.order.samples.txt. The only warning message was about the NumPy version.

Command 2 failed instantly and didn’t even generate the smooth.final.pggb.ordhstgrw.bp.tsv file. The error message was the same as before.

It would be really helpful if the Panacus team could fix this bug for the research community.

Kind regards,

Taek

**Comment by heringerp** [comment]
Hi Taek,

could you try the "From repository" option? The binary release is unfortunately the same version as the conda version.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

This time was more productive.

I tried both Command 1 and Command 2, and only Command 2 worked. I used -l 2,4,6,15,10, and the plot displayed different color bar patterns nicely. I hope this is the correct way to visualize the plot—please let me know if it's not.

![image](https://github.com/user-attachments/assets/da99c0fd-5b44-494c-826c-b49c2f50fbde)


Also, it would be helpful for others if the manual provided more clarity on this visualisation issue.

Once again, thank you for your help!

Cheers,

Taek

**Comment by heringerp** [comment]
Hi Taek,

yes, that looks good. 

Yes, there is currently work on a new release done, so that should fix the problem also for all other versions of panancus.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter,

I have a quick question.

After generating each community growth plot, I merged all the GFA files from PGGB into a single global GFA file to create a global genome growth plot. However, when I tried to use the same Panacus command for the ordered growth plot, I encountered an error.

[2024-08-30T08:04:01Z INFO  panacus::graph] constructing indexes for node/edge IDs, node lengths, and P/W lines..
[2024-08-30T08:04:01Z INFO  panacus::io] loading graph from /g/data/chrAll_ncig_hprc.smooth.final.gfa
thread 'main' panicked at src/graph.rs:330:21:
Segment with ID 1 occurs multiple times in GFA
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Do you have any suggestions for resolving this?

Thanks,

Taek

**Comment by danydoerr** [comment]
Concatenating GFA files doesn't work, because you will end up with different segments being assigned the same ID, and you end up with an invalid graph. You need to use `odgi squeeze` or `vg combine` for that.

**Comment by OZTaekOppa** [comment]
@danydoerr 

Thank you for getting back to me.

Here’s what I’ve done so far:
1. Merged individual GFA files (generated from PGGB) using vg combine with and without the -p option:
vg combine smp1.gfa smp2.gfa > merged_all.gfa   

2. Executed Panacus for the merged merged_all.gfa:
Exclude paths from reference genome CHM13 and GRCH38
grep '^P' ${INPUT_GFA} | cut -f2 | grep -iE 'chm13|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt

Unfortunately, it failed after 2-3 minutes without any specific error message.

+ grep '^P' /merged_all.gfa
+ cut -f2
+ grep -iE 'chm13|grch38'

======================================================================================
                  Resource Usage on 2024-09-06 10:52:07:
   Job Id:             124328844.gadi-pbs
   Project:            te53
   Exit Status:        1
   Service Units:      1.49
   NCPUs Requested:    16                     NCPUs Used: 16
                                           CPU Time Used: 00:00:50
   Memory Requested:   160.0GB               Memory Used: 42.82GB
   Walltime requested: 24:00:00            Walltime Used: 00:01:07
   JobFS requested:    1.0GB                  JobFS used: 0B
======================================================================================


3. Manual check for the merged merged_all.gfa:
grep '^P' ./merged_all.gfa | cut -f2 | grep -iE 'chm13\|grch38' > ./test1.pggb.path.txt
grep '^P' ./merged_all.gfa | cut -f2 | grep -ve 'chm13\|grch38' > ./test2.pggb.path.txt

 
Both attempts generated empty text files.

Do you have any suggestions for resolving this?

Thanks.

Taek

**Comment by danydoerr** [comment]
Hey Taek,
I am not sure if you can actually run `vg combine` on GFA graphs. I suspect you need to convert those first into vg's own file format. You can then also check the correctness of the combined graph with `vg validate`. 
-dany

**Comment by OZTaekOppa** [comment]
@danydoerr 

Thank you for your reply.

I will test the conversion for all merged chromosome GFA files.

I have a question:
For the -l option, I used 2, 6, and 49, with -q set to 0. My understanding is that HG002#1 and HG002#2 are treated as two haplotypes, and the -l 2 option means any two haplotypes (nodes or paths) are used to generate growth. This command produced a TSV file.

RUST_LOG=info ${PANACUS} ordered-histgrowth -c bp -t${PBS_NCPUS} -l 2,6,49 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ng1.ordhstgrw.bp.tsv

I want to check the correlation between CHM13 (each chromosome length) and the accumulated base pairs in the TSV file’s last row (-l 2). From what I understand, the last row should reflect the total accumulated length, which should be similar to the length of each CHM13 chromosome. Is that correct?



I encountered an error with the following command:
For the -l option, I used 1, 2, and 54, with -q set to 0.

There was a numpy version issue in our default module, so I installed a separate Python environment with these versions:
python=3.9.2, numpy=1.22.0, scipy=1.8.0, matplotlib=3.5.1, pandas=1.4.3, seaborn=0.12.0, and scikit-learn=1.1.1.
However, I’m still getting the same error. 

[2024-09-09T09:35:25Z INFO  panacus::abacus] abacus has 57 path groups and 8701826 countables
[2024-09-09T09:35:25Z INFO  panacus::io] reporting ordered-growth table
[2024-09-09T09:35:25Z INFO  panacus::io] calculating ordered growth for coverage >= 2A and quorum >= 0R
[2024-09-09T09:35:25Z INFO  panacus::io] calculating ordered growth for coverage >= 1A and quorum >= 0R
[2024-09-09T09:35:25Z INFO  panacus::io] calculating ordered growth for coverage >= 54A and quorum >= 0R
[2024-09-09T09:35:30Z INFO  panacus] done; time elapsed: 70.026912399s
+ /g/data/panacus/scripts/panacus-visualize.py -e /g/data/ng2_ordered/chr1.fasta.gz.c1c4fa2.3db5bc7.8fd4bd5.smooth.final.pggb.ng2.ordhstgrw.bp.tsv
Traceback (most recent call last):
  File "/g/data/panacus/scripts/panacus-visualize.py", line 260, in <module>
    plot_growth(df_tc, axs_tc, loc=args.legend_location, estimate_growth=args.estimate_growth_params)
  File "/g/data/panacus/scripts/panacus-visualize.py", line 120, in plot_growth
    popt, curve = fit_gamma(df.loc[1:, (t, ct, c,q)].array)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 1140, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 843, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 942, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 1180, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexing.py", line 1214, in _get_slice_axis
    indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop, slice_obj.step)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6274, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6484, in slice_locs
    start_slice = self.get_slice_bound(start, "left")
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6393, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side)
  File "/g/data/condapkg/envs/python3_v392/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6340, in _maybe_cast_slice_bound
    raise self._invalid_indexer("slice", label)
TypeError: cannot do slice indexing on Index with these indexers [1] of type int


Is there any way to resolve this? 
Or does the Ordered growth require a minimum of -l 2? If yes, why is that?

Thanks.

Taek

**Comment by heringerp** [comment]
Hi Taek,

the `-l` option describes the coverage needed for a feature to be included in the calculation. In the case of `-l 2` it does not mean that only two haplotypes are used, but instead that only nodes (or edges) are used in the calculation (i.e. for the calculation of every single bar/row) that are visited by at least two haplotypes (and possibly more).

Yes, the last line should show the total number of features (nodes/edges/bps) of the whole graph.

No, ordered-growth does not require a minimum `-l` of 2, it should work with all values. Unfortunately, the issue you encountered is a bug with the `-e` parameter of panacus-visualize. I have created a PR for this (#36), but until it is merged you can avoid this by not using `-e` for panacus-visualize (no curve will be fitted).

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Thank you, Peter! Please let me know if the code is updated. 
Cheers,
Taek

**Comment by danydoerr** [comment]
We just pushed a new release.

**Comment by OZTaekOppa** [comment]
Hi @danydoerr and @heringerp, 

I tried both approaches after reinstalling the latest version via bioconda (v.0.2.4) and the repository.
Here’s the script I used for the "Ordered Histgrowth."

Step 1: Establish the order of samples in the growth statistics (ARF, AMR, EUR, SAS, EAS, NCIG)
echo 'HG01891 HG02109 HG02145 HG02257 ……' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.order.samples.txt

Step 2: Establish the exclude of samples in the growth statistics
echo 'chm13 grch38' | tr ' ' '\n' > ${OUTPUT_DIR}/pggb_hprc.exculde.samples.txt

Step 3: Exclude paths from reference genome CHM13 and GRCH38
grep '^P' ${INPUT_GFA} | cut -f2 | grep -iE 'chm13|grch38' > ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt

Step 4: panacus histgrowth to calculate coverage and pangenome growth for nodes
RUST_LOG=info panacus ordered-histgrowth -c bp -t${PBS_NCPUS} -l 1,2,4,49 -S -e ${OUTPUT_DIR}/${BASEFILE}.pggb.path.txt -O ${OUTPUT_DIR}/pggb_hprc.order.samples.txt ${INPUT_GFA} > ${OUTPUT_DIR}/${BASEFILE}.pggb.ng0.ordhstgrw.bp.tsv

Step 5: Visualize coverage histogram and pangenome growth curve with estimated growth parameters
panacus-visualize -e ${OUTPUT_DIR}/${BASEFILE}.pggb.ng0.ordhstgrw.bp.tsv > ${OUTPUT_DIR}/${BASEFILE}.pggb.ng0.ordhstgrw.bp.pdf 
Everything worked fine up to Step 4, but in Step 5, it failed with the following error message:

+ /g/data/panacus/scripts/panacus-visualize.py -e /g/data/ analyses/panacus/PGGB/ng0/chr1.fasta.gz.smooth.final.pggb.ng0.ordhstgrw.bp.tsv
This script cannot visualize the content of this type of table, exiting.


Even when I specified the file path (/g/data/panacus/scripts/panacus-visualize.py) instead of using panacus-visualise, the error remained the same.

Any suggestions?

Kind regards,

Taek

**Comment by heringerp** [comment]
Hi Taek,

the problem is that heaps law as an estimation cannot be used with an ordered histgrowth, so the `-e` parameter of panacus-visualize does not work for these tables.

Try
```
/g/data/panacus/scripts/panacus-visualize.py /g/data/analyses/panacus/PGGB/ng0/chr1.fasta.gz.smooth.final.pggb.ng0.ordhstgrw.bp.tsv
``` 
instead.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
@heringerp,

Unfortunately, neither approach (panacus-visualize and panacus-visualize.py) worked. It was the same error message.

This script cannot visualize the content of this type of table, exiting.

Cheers,

Taek

**Comment by heringerp** [comment]
Hi Taek,

seems like there was unfortunately a bug in the panacus-visualize script. I pushed a new version of this script to the main-branch of the repo. If you use this new version of the script it should hopefully work.

Best regards
Peter

**Comment by OZTaekOppa** [comment]
Hi Peter and Danny,

Thank you for your help on this matter. 
It worked well. I'll keep you updated here if there are any further questions or new ideas.

Cheers,

Taek
